name: Build ASP.Net Core application

on:
  push:
    branches:
    - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release
